table_resource:
  type: sql
  json_dir: tables.json
  includes: feedbacks,users
#  excludes: feedbacks,users
  db:
    lang: postgres
    host: localhost
    username: postgres
    password: root
    port: 5432
    database: boa
frame:
  lang: go
  web: gin
  orm: gorm
  front_lib: vue
  ui: element
output:
  view: /Users/chen/Code/gen-code/temp/view
  handler:  /Users/chen/Code/gen-code/temp/hanlder
  protocol: /Users/chen/Code/gen-code/temp/protocol
  model: /Users/chen/Code/gen-code/temp/model
template_dir: .

